# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExamplePod' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExamplePod
pod 'Custom_pod',:path =>"../Custom_pod"
end
